defaults:
  - _self_
  - model: BERT_TGT
  - data: Eurlex-4k

tasks: [ "eval" ]


trainer:
  max_epochs: 16
  gpus: 1
  patience: 7
  min_delta: 0.03
  precision: 32
  fast_dev_run: False
  progress_bar_refresh_rate: 1

log:
  dir: resource/log/

model_checkpoint:
  dir: resource/model_checkpoint/

ranking:
  dir: resource/ranking/

attention:
  dir: resource/attention
  sample_id: 0

prediction:
  dir: resource/prediction/${model.name}_${data.name}/
  fold: 0
  write_interval: batch

result:
  dir: resource/result/

eval:
  metrics: ["mrr","ndcg","precision","recall"]
  thresholds: [1,5,10]
  num_nearest_neighbors: 10
  label_cls: ["all", "full", "few", "tail"]
  index:
    M: 256
    indexThreadQty: ${data.num_workers}
    efConstruction: 2048
    post: 2









