defaults:
  - _self_
  - model: BERT_TGT
  - data: EURLEX57K

tasks: [ "fit" ]


trainer:
  max_epochs: 32
  gpus: 1
  patience: 15
  min_delta: 0.03
  precision: 16
  fast_dev_run: False
  progress_bar_refresh_rate: 1

log:
  dir: resource/log/

model_checkpoint:
  dir: resource/model_checkpoint/

ranking:
  dir: resource/ranking/

attention:
  dir: resource/attention
  sample_id: 0

prediction:
  dir: resource/prediction/${model.name}_${data.name}/
  fold: 0
  write_interval: batch

tsne:
  dir: resource/tsne/${model.name}_${data.name}/
  fold_id: 0

stat:
  dir: resource/stat/








